### ISSUE TITLE
ChartViewer control cannot be printed

### ISSUE THREAD

**Issue by msdvoits** [predictionmachines/InteractiveDataDisplay#24]
In different browser it looks in different way, but still incorrectly: layout is shifted, some parts disappear.

**How to reproduce**
1. Open `samples/viewer/Error Bars.html` in Chrome

![image](https://cloud.githubusercontent.com/assets/16209677/13391652/a4446b54-dee6-11e5-820f-b113af398920.png)
1. Run command Print... (Ctrl + P) and see the page preview.

![image](https://cloud.githubusercontent.com/assets/16209677/13391677/c69a0538-dee6-11e5-9d88-430ec73ed000.png)

Expected: The preview should look similar to the browser window.

Observed: The preview image has following issues:
- Only part of IDD chart is shown (no left axis, it is obviously zoomed in)
- No control panel at the right

**Comment by vassilyl** [comment]
I suggest we do not print the control panel on the right. It should be properly hidden using media rule.

**Comment by ElenaPochernina** [comment]
1. Control panel, hide/show left panel button aren't shown because they have an image on the background. They can be printed if you change the browser's print settings (option "print background"). 
2. To not print the right control panel, we can write in .css file:
 
 ```
@media print {
        .no-print, .no-print *
        {
            display: none !important;
        }
    }
```
And then add this class to element which contains right control panel.
3. Chart is shown in part (no left axis and it is zoomed in) if `width` or `height` of div-element are given in percent.

**Comment by dgrechka** [comment]
Seems to be fixed.

Axes are visible. Controls are hidden. Legend and probe info is visible.

![image](https://user-images.githubusercontent.com/5637547/51532056-2e07f080-1e50-11e9-97bf-b40e7ba88818.png)
